<?php

namespace ContainerSNSy2vv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WGb7qROService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wGb7qRO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wGb7qRO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'escapeGameRepository' => ['privates', 'App\\Repository\\EscapeGameRepository', 'getEscapeGameRepositoryService', true],
        ], [
            'escapeGameRepository' => 'App\\Repository\\EscapeGameRepository',
        ]);
    }
}
