<?php

namespace ContainerB9Aw24q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_R_5QKV7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R.5QKV7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R.5QKV7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminController::delete' => ['privates', '.service_locator.6eVqP1n', 'get_ServiceLocator_6eVqP1nService', true],
            'App\\Controller\\AdminController::edit' => ['privates', '.service_locator.6eVqP1n', 'get_ServiceLocator_6eVqP1nService', true],
            'App\\Controller\\AdminController::index' => ['privates', '.service_locator.GqNWkCX', 'get_ServiceLocator_GqNWkCXService', true],
            'App\\Controller\\AdminController::show' => ['privates', '.service_locator.6eVqP1n', 'get_ServiceLocator_6eVqP1nService', true],
            'App\\Controller\\EscapeGameController::delete' => ['privates', '.service_locator.TWanN1J', 'get_ServiceLocator_TWanN1JService', true],
            'App\\Controller\\EscapeGameController::edit' => ['privates', '.service_locator.TWanN1J', 'get_ServiceLocator_TWanN1JService', true],
            'App\\Controller\\EscapeGameController::index' => ['privates', '.service_locator.wGb7qRO', 'get_ServiceLocator_WGb7qROService', true],
            'App\\Controller\\EscapeGameController::show' => ['privates', '.service_locator.TWanN1J', 'get_ServiceLocator_TWanN1JService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\AdminController:delete' => ['privates', '.service_locator.6eVqP1n', 'get_ServiceLocator_6eVqP1nService', true],
            'App\\Controller\\AdminController:edit' => ['privates', '.service_locator.6eVqP1n', 'get_ServiceLocator_6eVqP1nService', true],
            'App\\Controller\\AdminController:index' => ['privates', '.service_locator.GqNWkCX', 'get_ServiceLocator_GqNWkCXService', true],
            'App\\Controller\\AdminController:show' => ['privates', '.service_locator.6eVqP1n', 'get_ServiceLocator_6eVqP1nService', true],
            'App\\Controller\\EscapeGameController:delete' => ['privates', '.service_locator.TWanN1J', 'get_ServiceLocator_TWanN1JService', true],
            'App\\Controller\\EscapeGameController:edit' => ['privates', '.service_locator.TWanN1J', 'get_ServiceLocator_TWanN1JService', true],
            'App\\Controller\\EscapeGameController:index' => ['privates', '.service_locator.wGb7qRO', 'get_ServiceLocator_WGb7qROService', true],
            'App\\Controller\\EscapeGameController:show' => ['privates', '.service_locator.TWanN1J', 'get_ServiceLocator_TWanN1JService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\AdminController::delete' => '?',
            'App\\Controller\\AdminController::edit' => '?',
            'App\\Controller\\AdminController::index' => '?',
            'App\\Controller\\AdminController::show' => '?',
            'App\\Controller\\EscapeGameController::delete' => '?',
            'App\\Controller\\EscapeGameController::edit' => '?',
            'App\\Controller\\EscapeGameController::index' => '?',
            'App\\Controller\\EscapeGameController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\AdminController:delete' => '?',
            'App\\Controller\\AdminController:edit' => '?',
            'App\\Controller\\AdminController:index' => '?',
            'App\\Controller\\AdminController:show' => '?',
            'App\\Controller\\EscapeGameController:delete' => '?',
            'App\\Controller\\EscapeGameController:edit' => '?',
            'App\\Controller\\EscapeGameController:index' => '?',
            'App\\Controller\\EscapeGameController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
