<?php

namespace ContainerB9Aw24q;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEscapeGameService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TWanN1J.App\Entity\EscapeGame' shared service.
     *
     * @return \App\Entity\EscapeGame
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TWanN1J": it references class "App\\Entity\\EscapeGame" but no such service exists.');
    }
}
