<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSNSy2vv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSNSy2vv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSNSy2vv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSNSy2vv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSNSy2vv\App_KernelDevDebugContainer([
    'container.build_hash' => 'SNSy2vv',
    'container.build_id' => '3f027700',
    'container.build_time' => 1601638124,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSNSy2vv');
